/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated/register'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedCitizenIndexRouteImport } from './routes/_authenticated/citizen.index'
import { Route as AuthenticatedCitizenAssistantRouteImport } from './routes/_authenticated/citizen.assistant'
import { Route as AuthenticatedCitizenLawyersRouteImport } from './routes/_authenticated/citizen.lawyers'
import { Route as AuthenticatedCitizenMessagesRouteImport } from './routes/_authenticated/citizen.messages'
import { Route as AuthenticatedCitizenNewRouteImport } from './routes/_authenticated/citizen.new'
import { Route as AuthenticatedCitizenProfileRouteImport } from './routes/_authenticated/citizen.profile'
import { Route as AuthenticatedEnforcementIndexRouteImport } from './routes/_authenticated/enforcement.index'
import { Route as AuthenticatedJudicialIndexRouteImport } from './routes/_authenticated/judicial.index'
import { Route as AuthenticatedLawyerIndexRouteImport } from './routes/_authenticated/lawyer.index'
import { Route as AuthenticatedLawyerProfileRouteImport } from './routes/_authenticated/lawyer.profile'
import { Route as AuthenticatedCitizenCaseCaseIdRouteImport } from './routes/_authenticated/citizen.case.$caseId'
import { Route as AuthenticatedJudicialCaseCaseIdRouteImport } from './routes/_authenticated/judicial.case.$caseId'
import { Route as AuthenticatedLawyerCaseCaseIdRouteImport } from './routes/_authenticated/lawyer.case.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/admin/verifications',
    path: '/admin/verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenIndexRoute =
  AuthenticatedCitizenIndexRouteImport.update({
    id: '/citizen/',
    path: '/citizen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenAssistantRoute =
  AuthenticatedCitizenAssistantRouteImport.update({
    id: '/citizen/assistant',
    path: '/citizen/assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenLawyersRoute =
  AuthenticatedCitizenLawyersRouteImport.update({
    id: '/citizen/lawyers',
    path: '/citizen/lawyers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenMessagesRoute =
  AuthenticatedCitizenMessagesRouteImport.update({
    id: '/citizen/messages',
    path: '/citizen/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenNewRoute = AuthenticatedCitizenNewRouteImport.update({
  id: '/citizen/new',
  path: '/citizen/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitizenProfileRoute =
  AuthenticatedCitizenProfileRouteImport.update({
    id: '/citizen/profile',
    path: '/citizen/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnforcementIndexRoute =
  AuthenticatedEnforcementIndexRouteImport.update({
    id: '/enforcement/',
    path: '/enforcement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJudicialIndexRoute =
  AuthenticatedJudicialIndexRouteImport.update({
    id: '/judicial/',
    path: '/judicial/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLawyerIndexRoute =
  AuthenticatedLawyerIndexRouteImport.update({
    id: '/lawyer/',
    path: '/lawyer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLawyerProfileRoute =
  AuthenticatedLawyerProfileRouteImport.update({
    id: '/lawyer/profile',
    path: '/lawyer/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCitizenCaseCaseIdRoute =
  AuthenticatedCitizenCaseCaseIdRouteImport.update({
    id: '/citizen/case/$caseId',
    path: '/citizen/case/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJudicialCaseCaseIdRoute =
  AuthenticatedJudicialCaseCaseIdRouteImport.update({
    id: '/judicial/case/$caseId',
    path: '/judicial/case/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLawyerCaseCaseIdRoute =
  AuthenticatedLawyerCaseCaseIdRouteImport.update({
    id: '/lawyer/case/$caseId',
    path: '/lawyer/case/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gateway': typeof GatewayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/citizen/assistant': typeof AuthenticatedCitizenAssistantRoute
  '/citizen/lawyers': typeof AuthenticatedCitizenLawyersRoute
  '/citizen/messages': typeof AuthenticatedCitizenMessagesRoute
  '/citizen/new': typeof AuthenticatedCitizenNewRoute
  '/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/lawyer/profile': typeof AuthenticatedLawyerProfileRoute
  '/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/enforcement/': typeof AuthenticatedEnforcementIndexRoute
  '/judicial/': typeof AuthenticatedJudicialIndexRoute
  '/lawyer/': typeof AuthenticatedLawyerIndexRoute
  '/citizen/case/$caseId': typeof AuthenticatedCitizenCaseCaseIdRoute
  '/judicial/case/$caseId': typeof AuthenticatedJudicialCaseCaseIdRoute
  '/lawyer/case/$caseId': typeof AuthenticatedLawyerCaseCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gateway': typeof GatewayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/citizen/assistant': typeof AuthenticatedCitizenAssistantRoute
  '/citizen/lawyers': typeof AuthenticatedCitizenLawyersRoute
  '/citizen/messages': typeof AuthenticatedCitizenMessagesRoute
  '/citizen/new': typeof AuthenticatedCitizenNewRoute
  '/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/lawyer/profile': typeof AuthenticatedLawyerProfileRoute
  '/citizen': typeof AuthenticatedCitizenIndexRoute
  '/enforcement': typeof AuthenticatedEnforcementIndexRoute
  '/judicial': typeof AuthenticatedJudicialIndexRoute
  '/lawyer': typeof AuthenticatedLawyerIndexRoute
  '/citizen/case/$caseId': typeof AuthenticatedCitizenCaseCaseIdRoute
  '/judicial/case/$caseId': typeof AuthenticatedJudicialCaseCaseIdRoute
  '/lawyer/case/$caseId': typeof AuthenticatedLawyerCaseCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/gateway': typeof GatewayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/citizen/assistant': typeof AuthenticatedCitizenAssistantRoute
  '/_authenticated/citizen/lawyers': typeof AuthenticatedCitizenLawyersRoute
  '/_authenticated/citizen/messages': typeof AuthenticatedCitizenMessagesRoute
  '/_authenticated/citizen/new': typeof AuthenticatedCitizenNewRoute
  '/_authenticated/citizen/profile': typeof AuthenticatedCitizenProfileRoute
  '/_authenticated/lawyer/profile': typeof AuthenticatedLawyerProfileRoute
  '/_authenticated/citizen/': typeof AuthenticatedCitizenIndexRoute
  '/_authenticated/enforcement/': typeof AuthenticatedEnforcementIndexRoute
  '/_authenticated/judicial/': typeof AuthenticatedJudicialIndexRoute
  '/_authenticated/lawyer/': typeof AuthenticatedLawyerIndexRoute
  '/_authenticated/citizen/case/$caseId': typeof AuthenticatedCitizenCaseCaseIdRoute
  '/_authenticated/judicial/case/$caseId': typeof AuthenticatedJudicialCaseCaseIdRoute
  '/_authenticated/lawyer/case/$caseId': typeof AuthenticatedLawyerCaseCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gateway'
    | '/reset-password'
    | '/register'
    | '/admin/verifications'
    | '/citizen/assistant'
    | '/citizen/lawyers'
    | '/citizen/messages'
    | '/citizen/new'
    | '/citizen/profile'
    | '/lawyer/profile'
    | '/citizen/'
    | '/enforcement/'
    | '/judicial/'
    | '/lawyer/'
    | '/citizen/case/$caseId'
    | '/judicial/case/$caseId'
    | '/lawyer/case/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gateway'
    | '/reset-password'
    | '/register'
    | '/admin/verifications'
    | '/citizen/assistant'
    | '/citizen/lawyers'
    | '/citizen/messages'
    | '/citizen/new'
    | '/citizen/profile'
    | '/lawyer/profile'
    | '/citizen'
    | '/enforcement'
    | '/judicial'
    | '/lawyer'
    | '/citizen/case/$caseId'
    | '/judicial/case/$caseId'
    | '/lawyer/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/gateway'
    | '/reset-password'
    | '/_authenticated/register'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/citizen/assistant'
    | '/_authenticated/citizen/lawyers'
    | '/_authenticated/citizen/messages'
    | '/_authenticated/citizen/new'
    | '/_authenticated/citizen/profile'
    | '/_authenticated/lawyer/profile'
    | '/_authenticated/citizen/'
    | '/_authenticated/enforcement/'
    | '/_authenticated/judicial/'
    | '/_authenticated/lawyer/'
    | '/_authenticated/citizen/case/$caseId'
    | '/_authenticated/judicial/case/$caseId'
    | '/_authenticated/lawyer/case/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GatewayRoute: typeof GatewayRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/': {
      id: '/_authenticated/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof AuthenticatedCitizenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/assistant': {
      id: '/_authenticated/citizen/assistant'
      path: '/citizen/assistant'
      fullPath: '/citizen/assistant'
      preLoaderRoute: typeof AuthenticatedCitizenAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/lawyers': {
      id: '/_authenticated/citizen/lawyers'
      path: '/citizen/lawyers'
      fullPath: '/citizen/lawyers'
      preLoaderRoute: typeof AuthenticatedCitizenLawyersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/messages': {
      id: '/_authenticated/citizen/messages'
      path: '/citizen/messages'
      fullPath: '/citizen/messages'
      preLoaderRoute: typeof AuthenticatedCitizenMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/new': {
      id: '/_authenticated/citizen/new'
      path: '/citizen/new'
      fullPath: '/citizen/new'
      preLoaderRoute: typeof AuthenticatedCitizenNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/profile': {
      id: '/_authenticated/citizen/profile'
      path: '/citizen/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof AuthenticatedCitizenProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enforcement/': {
      id: '/_authenticated/enforcement/'
      path: '/enforcement'
      fullPath: '/enforcement/'
      preLoaderRoute: typeof AuthenticatedEnforcementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judicial/': {
      id: '/_authenticated/judicial/'
      path: '/judicial'
      fullPath: '/judicial/'
      preLoaderRoute: typeof AuthenticatedJudicialIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lawyer/': {
      id: '/_authenticated/lawyer/'
      path: '/lawyer'
      fullPath: '/lawyer/'
      preLoaderRoute: typeof AuthenticatedLawyerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lawyer/profile': {
      id: '/_authenticated/lawyer/profile'
      path: '/lawyer/profile'
      fullPath: '/lawyer/profile'
      preLoaderRoute: typeof AuthenticatedLawyerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen/case/$caseId': {
      id: '/_authenticated/citizen/case/$caseId'
      path: '/citizen/case/$caseId'
      fullPath: '/citizen/case/$caseId'
      preLoaderRoute: typeof AuthenticatedCitizenCaseCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judicial/case/$caseId': {
      id: '/_authenticated/judicial/case/$caseId'
      path: '/judicial/case/$caseId'
      fullPath: '/judicial/case/$caseId'
      preLoaderRoute: typeof AuthenticatedJudicialCaseCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lawyer/case/$caseId': {
      id: '/_authenticated/lawyer/case/$caseId'
      path: '/lawyer/case/$caseId'
      fullPath: '/lawyer/case/$caseId'
      preLoaderRoute: typeof AuthenticatedLawyerCaseCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedCitizenAssistantRoute: typeof AuthenticatedCitizenAssistantRoute
  AuthenticatedCitizenLawyersRoute: typeof AuthenticatedCitizenLawyersRoute
  AuthenticatedCitizenMessagesRoute: typeof AuthenticatedCitizenMessagesRoute
  AuthenticatedCitizenNewRoute: typeof AuthenticatedCitizenNewRoute
  AuthenticatedCitizenProfileRoute: typeof AuthenticatedCitizenProfileRoute
  AuthenticatedLawyerProfileRoute: typeof AuthenticatedLawyerProfileRoute
  AuthenticatedCitizenIndexRoute: typeof AuthenticatedCitizenIndexRoute
  AuthenticatedEnforcementIndexRoute: typeof AuthenticatedEnforcementIndexRoute
  AuthenticatedJudicialIndexRoute: typeof AuthenticatedJudicialIndexRoute
  AuthenticatedLawyerIndexRoute: typeof AuthenticatedLawyerIndexRoute
  AuthenticatedCitizenCaseCaseIdRoute: typeof AuthenticatedCitizenCaseCaseIdRoute
  AuthenticatedJudicialCaseCaseIdRoute: typeof AuthenticatedJudicialCaseCaseIdRoute
  AuthenticatedLawyerCaseCaseIdRoute: typeof AuthenticatedLawyerCaseCaseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedCitizenAssistantRoute: AuthenticatedCitizenAssistantRoute,
  AuthenticatedCitizenLawyersRoute: AuthenticatedCitizenLawyersRoute,
  AuthenticatedCitizenMessagesRoute: AuthenticatedCitizenMessagesRoute,
  AuthenticatedCitizenNewRoute: AuthenticatedCitizenNewRoute,
  AuthenticatedCitizenProfileRoute: AuthenticatedCitizenProfileRoute,
  AuthenticatedLawyerProfileRoute: AuthenticatedLawyerProfileRoute,
  AuthenticatedCitizenIndexRoute: AuthenticatedCitizenIndexRoute,
  AuthenticatedEnforcementIndexRoute: AuthenticatedEnforcementIndexRoute,
  AuthenticatedJudicialIndexRoute: AuthenticatedJudicialIndexRoute,
  AuthenticatedLawyerIndexRoute: AuthenticatedLawyerIndexRoute,
  AuthenticatedCitizenCaseCaseIdRoute: AuthenticatedCitizenCaseCaseIdRoute,
  AuthenticatedJudicialCaseCaseIdRoute: AuthenticatedJudicialCaseCaseIdRoute,
  AuthenticatedLawyerCaseCaseIdRoute: AuthenticatedLawyerCaseCaseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GatewayRoute: GatewayRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
