// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'




function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env['SUPABASE_URL'] || process.env['VITE_SUPABASE_URL'] || 'https://zxaffdbhofgstbgyuucd.supabase.co';
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'] || process.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || 'sb_publishable_SARI0YV0JApWXOkpcNzsBg_QOZz5ZUn';

    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (authHeader === 'Bearer demo-judicial-token' || authHeader?.includes('demo-judicial')) {
      const demoSupabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );
      return next({
        context: {
          supabase: demoSupabase,
          userId: 'd3000000-0000-0000-0000-000000000001',
          claims: {
            sub: 'd3000000-0000-0000-0000-000000000001',
            email: 'justice.mehta@parthsarathi.in',
            user_metadata: { full_name: "Hon'ble Justice A. Mehta" },
            phone: '9800011223',
            phone_confirmed_at: new Date().toISOString(),
          },
        },
      });
    }

    if (authHeader === 'Bearer demo-lawyer-token' || authHeader?.includes('demo-lawyer')) {
      const demoSupabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );
      return next({
        context: {
          supabase: demoSupabase,
          userId: 'u1000000-0000-0000-0000-000000000001',
          claims: {
            sub: 'u1000000-0000-0000-0000-000000000001',
            email: 'advocate.rajesh@parthsarathi.in',
            user_metadata: { full_name: 'Adv. Rajesh V. Sharma' },
            phone: '9811002233',
            phone_confirmed_at: new Date().toISOString(),
          },
        },
      });
    }

    if (authHeader === 'Bearer demo-citizen-token' || authHeader?.includes('demo-citizen')) {
      const demoSupabase = createClient<Database>(
        SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY,
        {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );
      return next({
        context: {
          supabase: demoSupabase,
          userId: '511da54d-3f78-47b6-97e4-9e56e1c0b8fc',
          claims: {
            sub: '511da54d-3f78-47b6-97e4-9e56e1c0b8fc',
            email: 'demo.citizen@gmail.com',
            user_metadata: { full_name: 'Demo Citizen' },
            phone: '9876543210',
            phone_confirmed_at: new Date().toISOString(),
          },
        },
      });
    }

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
