// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export const DEMO_CITIZEN_USER: any = {
  id: "511da54d-3f78-47b6-97e4-9e56e1c0b8fc",
  aud: "authenticated",
  role: "authenticated",
  email: "demo.citizen@gmail.com",
  phone: "9876543210",
  app_metadata: { provider: "email", providers: ["email"] },
  user_metadata: { full_name: "Demo Citizen", phone: "9876543210" },
  created_at: "2026-09-11T18:12:49.034539Z",
  updated_at: "2026-09-11T18:12:49.034539Z",
};

export const DEMO_CITIZEN_SESSION: any = {
  access_token: "demo-citizen-token",
  token_type: "bearer",
  expires_in: 360000,
  refresh_token: "demo-citizen-refresh-token",
  user: DEMO_CITIZEN_USER,
};

export const DEMO_LAWYER_USER: any = {
  id: "u1000000-0000-0000-0000-000000000001",
  aud: "authenticated",
  role: "authenticated",
  email: "advocate.rajesh@parthsarathi.in",
  phone: "9811002233",
  app_metadata: { provider: "email", providers: ["email"] },
  user_metadata: { full_name: "Adv. Rajesh V. Sharma", phone: "9811002233" },
  created_at: "2026-09-11T18:12:49.034539Z",
  updated_at: "2026-09-11T18:12:49.034539Z",
};

export const DEMO_LAWYER_SESSION: any = {
  access_token: "demo-lawyer-token",
  token_type: "bearer",
  expires_in: 360000,
  refresh_token: "demo-lawyer-refresh-token",
  user: DEMO_LAWYER_USER,
};

export const DEMO_JUDICIAL_USER: any = {
  id: "d3000000-0000-0000-0000-000000000001",
  aud: "authenticated",
  role: "authenticated",
  email: "justice.mehta@parthsarathi.in",
  phone: "9800011223",
  app_metadata: { provider: "email", providers: ["email"] },
  user_metadata: { full_name: "Hon'ble Justice A. Mehta", phone: "9800011223" },
  created_at: "2026-09-11T18:12:49.034539Z",
  updated_at: "2026-09-11T18:12:49.034539Z",
};

export const DEMO_JUDICIAL_SESSION: any = {
  access_token: "demo-judicial-token",
  token_type: "bearer",
  expires_in: 360000,
  refresh_token: "demo-judicial-refresh-token",
  user: DEMO_JUDICIAL_USER,
};

function isDemoCitizen(): boolean {
  if (typeof window === "undefined") return false;
  return localStorage.getItem("parthsarathi_demo_citizen") === "true";
}

function isDemoLawyer(): boolean {
  if (typeof window === "undefined") return false;
  return localStorage.getItem("parthsarathi_demo_lawyer") === "true";
}

function isDemoJudicial(): boolean {
  if (typeof window === "undefined") return false;
  return localStorage.getItem("parthsarathi_demo_judicial") === "true";
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    const target = Reflect.get(_supabase, prop, receiver);
    if (prop === "auth") {
      return new Proxy(target, {
        get(authTarget, authProp, authReceiver) {
          if (authProp === "getUser") {
            if (isDemoJudicial()) return async () => ({ data: { user: DEMO_JUDICIAL_USER }, error: null });
            if (isDemoLawyer()) return async () => ({ data: { user: DEMO_LAWYER_USER }, error: null });
            if (isDemoCitizen()) return async () => ({ data: { user: DEMO_CITIZEN_USER }, error: null });
          }
          if (authProp === "getSession") {
            if (isDemoJudicial()) return async () => ({ data: { session: DEMO_JUDICIAL_SESSION }, error: null });
            if (isDemoLawyer()) return async () => ({ data: { session: DEMO_LAWYER_SESSION }, error: null });
            if (isDemoCitizen()) return async () => ({ data: { session: DEMO_CITIZEN_SESSION }, error: null });
          }
          if (authProp === "signOut") {
            return async () => {
              if (typeof window !== "undefined") {
                localStorage.removeItem("parthsarathi_demo_judicial");
                localStorage.removeItem("parthsarathi_demo_citizen");
                localStorage.removeItem("parthsarathi_demo_lawyer");
              }
              return authTarget.signOut();
            };
          }
          const val = Reflect.get(authTarget, authProp, authReceiver);
          return typeof val === "function" ? val.bind(authTarget) : val;
        },
      });
    }
    return target;
  },
});

